function [fitresult, gof] = createFit(Humidity, Temperatures, MuonDailyAve)
%CREATEFIT(HUMIDITY,TEMPERATURES,MUONDAILYAVE)
%  Create a fit.
%
%  Data for 'Muon Count Relation in Respect to Humidity and Temperature' fit:
%      X Input : Humidity
%      Y Input : Temperatures
%      Z Output: MuonDailyAve
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Apr-2017 17:29:03


%% Fit: 'Muon Count Relation in Respect to Humidity and Temperature'.
[xData, yData, zData] = prepareSurfaceData( Humidity, Temperatures, MuonDailyAve );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Muon Count Relation in Respect to Humidity and Temperature' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Muon Count Relation in Respect to Humidity and Temperature', 'MuonDailyAve vs. Humidity, Temperatures', 'Location', 'NorthEast' );
% Label axes
xlabel Humidity
ylabel Temperatures
zlabel MuonDailyAve
grid on
view( -83.9, 16.4 );


